# Base configs
baseurl: ""
# baseurl: "http://shikheronline.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-75681059-2"

# UI configs
title: "Photography by Shikher"
subtitle: "See the world through my eyes!"
author: "Shikher Verma"
header:
 title: "Photography"
 subtitle: "by Shikher"
footer:
 name: "Hey there, my name is Shikher :)"
 bio: "I am a recovering workaholic, slowly learning to appreciate the world of art. Or the world of unnecessary nonsense, as I used to discount it earlier! An alien investigator in the world of style, fashion and colors :D I am a minimalist, not by choice, IIT Kanpur makes everyone a minimalist! Minimalism basically means that I value experiences more than material posessions. So I travel all over the world looking for exciting new things to do. This picture of me is from when I volunteered for the fire show in Singapore Night Safari :)"
social_urls:
  instagram: "https://www.instagram.com/shikheronline"
  email: "shikhervermaonline+website@gmail.com"